export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1f1635",
        "primary-fixed": "#e9ddff",
        "on-background": "#e6e0e9",
        "outline-variant": "#494551",
        "inverse-on-surface": "#322f35",
        "on-primary": "#381e72",
        "on-surface": "#e6e0e9",
        "surface": "#141218",
        "on-tertiary-fixed": "#241a00",
        "tertiary-fixed-dim": "#e7c365",
        "tertiary-container": "#c9a74d",
        "secondary-fixed-dim": "#cdc0e9",
        "on-surface-variant": "#cbc4d2",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#36343a",
        "primary-fixed-dim": "#cfbcff",
        "error-container": "#93000a",
        "background": "#141218",
        "on-tertiary": "#3e2e00",
        "on-tertiary-fixed-variant": "#594400",
        "surface-tint": "#cfbcff",
        "secondary": "#cdc0e9",
        "surface-container-low": "#1d1b20",
        "on-primary-fixed": "#22005d",
        "surface-dim": "#141218",
        "on-secondary": "#342b4b",
        "secondary-fixed": "#e9ddff",
        "tertiary-fixed": "#ffdf93",
        "secondary-container": "#4d4465",
        "primary-container": "#6750a4",
        "outline": "#948e9c",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#4f378a",
        "on-secondary-fixed-variant": "#4b4263",
        "inverse-primary": "#6750a4",
        "surface-container-lowest": "#0f0d13",
        "inverse-surface": "#e6e0e9",
        "surface-container": "#211f24",
        "primary": "#cfbcff",
        "on-secondary-container": "#bfb2da",
        "surface-bright": "#3b383e",
        "on-primary-container": "#e0d2ff",
        "surface-variant": "#36343a",
        "surface-container-high": "#2b292f",
        "on-error": "#690005",
        "tertiary": "#e7c365",
        "on-tertiary-container": "#503d00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "container-max": "1440px",
        gutter: "16px",
        margin: "32px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "label-sm": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "headline-md": ["Space Grotesk"],
        "headline-xl": ["Space Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "0em", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.05em", fontWeight: "700" }],
      },
    },
  },
};